//
// Created by swinston on 8/19/20.
//

#include "CommonHelper.h"


namespace tools {
    std::string errorString(XrResult errorCode) {
        switch (errorCode)
        {
#define STR_CASE(r) case XR_ ##r: return #r
            STR_CASE(ERROR_RUNTIME_FAILURE);
            STR_CASE(ERROR_OUT_OF_MEMORY);
            STR_CASE(ERROR_API_VERSION_UNSUPPORTED);
            STR_CASE(ERROR_INITIALIZATION_FAILED);
            STR_CASE(ERROR_FUNCTION_UNSUPPORTED);
            STR_CASE(ERROR_FEATURE_UNSUPPORTED);
            STR_CASE(ERROR_EXTENSION_NOT_PRESENT);
            STR_CASE(ERROR_LIMIT_REACHED);
            STR_CASE(ERROR_SIZE_INSUFFICIENT);
            STR_CASE(ERROR_HANDLE_INVALID);
            STR_CASE(ERROR_INSTANCE_LOST);
            STR_CASE(ERROR_SESSION_RUNNING);
            STR_CASE(ERROR_SESSION_NOT_RUNNING);
            STR_CASE(ERROR_SESSION_LOST);
            STR_CASE(ERROR_SYSTEM_INVALID);
            STR_CASE(ERROR_PATH_INVALID);
            STR_CASE(ERROR_PATH_COUNT_EXCEEDED);
            STR_CASE(ERROR_PATH_FORMAT_INVALID);
            STR_CASE(ERROR_PATH_UNSUPPORTED);
            STR_CASE(ERROR_LAYER_INVALID);
            STR_CASE(ERROR_LAYER_LIMIT_EXCEEDED);
            STR_CASE(ERROR_SWAPCHAIN_RECT_INVALID);
            STR_CASE(ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED);
            STR_CASE(ERROR_ACTION_TYPE_MISMATCH);
            STR_CASE(ERROR_SESSION_NOT_READY);
            STR_CASE(ERROR_SESSION_NOT_STOPPING);
            STR_CASE(ERROR_TIME_INVALID);
            STR_CASE(ERROR_REFERENCE_SPACE_UNSUPPORTED);
            STR_CASE(ERROR_FILE_ACCESS_ERROR);
            STR_CASE(ERROR_FILE_CONTENTS_INVALID);
            STR_CASE(ERROR_FORM_FACTOR_UNSUPPORTED);
            STR_CASE(ERROR_FORM_FACTOR_UNAVAILABLE);
            STR_CASE(ERROR_API_LAYER_NOT_PRESENT);
            STR_CASE(ERROR_CALL_ORDER_INVALID);
            STR_CASE(ERROR_GRAPHICS_DEVICE_INVALID);
            STR_CASE(ERROR_POSE_INVALID);
            STR_CASE(ERROR_INDEX_OUT_OF_RANGE);
            STR_CASE(ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED);
            STR_CASE(ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED);
            STR_CASE(ERROR_NAME_DUPLICATED);
            STR_CASE(ERROR_NAME_INVALID);
            STR_CASE(ERROR_ACTIONSET_NOT_ATTACHED);
            STR_CASE(ERROR_ACTIONSETS_ALREADY_ATTACHED);
            STR_CASE(ERROR_LOCALIZED_NAME_DUPLICATED);
            STR_CASE(ERROR_LOCALIZED_NAME_INVALID);
            STR_CASE(ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR);
            STR_CASE(ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR);
            STR_CASE(ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT);
            STR_CASE(ERROR_VALIDATION_FAILURE);
#undef STR_CASE
            default:
                return "UNKNOWN_ERROR";
        }
    }
    std::string GetXrVersionString(XrVersion ver) {
        return std::to_string(XR_VERSION_MAJOR(ver)) + "." + std::to_string(XR_VERSION_MINOR(ver)) + "." + std::to_string(XR_VERSION_PATCH(ver));
    }
}